FizzBuzzApplication/FizzBuzzApplication/Models/FizzBuzzModel.cs
using FizzBuzzRuleEngine;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;


namespace FizzBuzzApplication.Models
{
    public class FizzBuzzModel
    {
        [Range(1, 1000)]
        [Display(Name = "Enter Upper Limit")]
        public int maxLimit { get; set; }
        public IList<FizzBuzzEntityList> listofNumber { get; set; }
    }
}

FizzBuzzApplication/FizzBuzzApplication/Controllers/FizzBuzzController.cs
using FizzBuzzApplication.Models;
using FizzBuzzRuleEngine;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FizzBuzzApplication.Controllers
{
    public class FizzBuzzController : Controller
    {
        IRuleHandler ruleHandlr;
        public FizzBuzzController(IRuleHandler rhs)
        {
            ruleHandlr = rhs;
        }
        
        public ViewResult FizzBuzzResult(FizzBuzzModel fizzbuzzModel)
        {
            if (ModelState.IsValid)
            {
                fizzbuzzModel.listofNumber = ruleHandlr.ExecuteRules(fizzbuzzModel.maxLimit);

            }
            return View("FizzBuzzResult", fizzbuzzModel);
        }
    }
}

FizzBuzzApplication/FizzBuzzApplication/Views/FizzBuzz/FizzBuzzResult.cshtml
@model FizzBuzzApplication.Models.FizzBuzzModel
@using FizzBuzzApplication.CustomHTMLHelper

@{
    ViewBag.Title = "Fizz-Buzz";
}


<h2 align="center">FIZZ-BUZZ</h2>
<link href="~/Content/FizzBuzz.css" rel="stylesheet" />
<script type="text/javascript" src="~/scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="~/scripts/Pagination.js"></script>

@using (Html.BeginForm("FizzBuzzResult", "FizzBuzz"))
{
    @Html.ValidationSummary(true)

    <div class="FizzBuzz" id="inputPanel">
        <div>
            @Html.LabelFor(model => model.maxLimit)
            @Html.TextBoxFor(model => model.maxLimit)
            @Html.ValidationMessageFor(model => model.maxLimit)
            <p>
                <input type="submit" value="Submit" />
            </p>
        </div>
    </div>

}
@if (Model != null && Model.listofNumber != null)
{
    int i = 0;
    <div class="FizzBuzz">
        <div id="resultPanel">
            <ul id="FizzBuzzResult">
                <li>
                    @foreach (var item in Model.listofNumber)
                    {
                        if (i % 20 == 0 && i != 0)
                        {
                            @: <li>
                        }
                        foreach (var item2 in item)
                        {
                            @Html.LabelWithCustomStyle(item2.displayText, item2.appliedRuleId)
                        }
                        <br />
                        i = i + 1;
                        if (i % 20 == 0)
                        {
                            @: </li>
                        }
                    }
                </ul>
                <center><span id="PageList" class="clear"></span></center>
            </div>

        </div>

}
<script type="text/javascript">
    $(document).ready(function () {
        $("#FizzBuzzResult").Pagination();
    });
</script>